create table Role (id_role serial primary key, name_role character(500) not null);
insert into Role (name_role) values ('superuser'); 
insert into Role (name_role) values ('administrator');
insert into Role (name_role) values ('manager');
insert into Role (name_role) values ('god');
select * from  category;
create table Users (id_user serial primary key, name_user character(500) not null, login character(500) not null, id_role int references role(id_role));
insert into users (name_user, login) values ('Vladimir Vladimirovich', 'VVP'); 
select * from  item;
update users values Set id_role = 4 where login = 'VVP';
insert into users (name_user, login, id_role) values ('Petya', 'Petro', 3 );
insert into users (name_user, login, id_role) values ('Vanya', 'Vano', 2 );
insert into users (name_user, login, id_role) values ('Andrew', 'Andrew', 1 );
create table Comments (id_comments serial primary key, description_comments character(500));
create table Item (id_item serial primary key, name_item character(500) not null);
ALTER table comments add COLUMN  id_item int references item (id_item);
create table Category (id_comments serial primary key, name_category character(500) not null);
insert into category (name_category) values ('Alarm');
insert into category (name_category) values ('Warning');
create table State (id_state serial primary key, status character(500) not null);
insert into state (status) values ('in work');
insert into state (status) values ('wait');
insert into state (status) values ('off');
alter table item add column  id_user int references users (id_user);
alter table item add column  id_category int references category (id_comments);
alter table item add column  id_state int references state (id_state);
ALTER TABLE category RENAME COLUMN id_comments   TO id_category;
insert into Item (name_item, id_user,id_category,id_state) values ( 'ABCD', 1, 2,1);
insert into Item (name_item, id_user,id_category,id_state) values ( 'ABC', 3, 2,2);
insert into Item (name_item, id_user,id_category,id_state) values ( 'AB', 2, 2,2);
create table Rules (id_rules serial primary key, name_rules character(100) not null, description character(1000) );
insert into Rules (name_rules) values ('write');
insert into Rules (name_rules) values ('read');
insert into Rules (name_rules) values ('read-write');
create table Attachs (id_attachs serial primary key, name_attachs character(100) not null, id_item int references item(id_item));
insert into attachs (name_attachs, id_item) values ('File A', 3);
create table Junction_table (id serial primary key, id_rules int references rules(id_rules),id_role int references role(id_role));
insert into Junction_table(id_rules, id_role) values ((select id_rules from Rules where name_rules='write'),(select id_role from Role where name_role='god'));
insert into Junction_table(id_rules, id_role) values ((select id_rules from Rules where name_rules='read'),(select id_role from Role where name_role='superuser'));
